
spring:
  application:
    name: service-gateway
  profiles:
  #active: limit_route
   active: elapse_route
  # active: rewritepath_route
  # active: cookie_route
  #active: header_route
  #active: after_route
server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
