spring:
  profiles: after_route

#Ê±¼ä
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:8765/hi
          predicates :
          - After=2020-01-20T17:42:47.789-07:00[America/Denver]